### ISSUE TITLE
Seeding чатика

### ISSUE THREAD

**Issue by Ferchke7** [TechPowerPartners/ZoomerMessanger.Backend#23]

**Comment by Ferchke7** [comment]
Добавь 3 чата для юзера victor и добавь ещё одного юзера для сиддинга, с сообщениями 3-4 штук!
Прошу быстрее!

**Comment by Maflend** [comment]
нельзя создать 3 чата для 3ех пользователей. Это невалидно
Чат создается между двумя людьми. И если чат между ними есть, создать еще один нельзя
